{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-service.fullname" . }}
data:
  dbHost: {{ .Values.db.host | quote }}
  dbPort: "{{ .Values.db.port | default "3306" }}"
{{- end }}