apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "demo-service.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "demo-service.fullname" . }}  # Replace with your service account name
roleRef:
  kind: Role
  name: {{ include "demo-service.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
