{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-service.fullname" . }}
type: Opaque
data:
  dbUser: {{ .Values.db.user | b64enc }}
  dbPassword: {{ .Values.db.password | b64enc }}
{{- end }}